version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=app.settings_docker
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db